on: 
  pull_request:
    branches: [master]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/checkout@v2
      with:
       repotoken: ${{ secrets.GITHUB_TOKEN }}
