# Container image that runs your code
FROM openjdk:8-alpine

RUN apk upgrade --update && \
	apk add bash curl

RUN curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.38.0/ktlint && chmod a+x ktlint

COPY executeCollectPrChanges /executeCollectPrChanges

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT /bin/bash /run-scripts.sh
